version: "3"
services:
    frontend:
      environment: 
         REACT_APP_HOST_SERVER: 192.168.2.212
         REACT_APP_PORT_SERVER: 5004
         PORT: 3004
      build:
        context: ./client
        dockerfile: Dockerfile
      container_name: cont-frontend-distinte-prod-0.0.1
      image: img-frontend-distinte-prod:0.0.1
      restart: always
      ports:
        - "3004:80"
    backend:
      environment:
        PORT: 5004
      build:
        context: ./server
        dockerfile: Dockerfile
      container_name: cont-backend-distinte-prod-0.0.1
      image: img-backend-distinte-prod:0.0.1
      restart: always
      ports:
          - "5004:5004"
